"""
Node-RED embedded runtime for 1052-OS gateway.

Spawns `node-red` as a child process so users can author new protocol drivers
(modbus / opc ua / s7 / ...) by dragging nodes in the editor and POSTing
results to ``/api/td/insert`` — zero Python changes required.

Lifecycle:
- start()           : non-blocking. Writes userDir/settings.js + flows.json on
                      first run, then Popen(node-red, --userDir, --port, --settings).
                      Idempotent: 2nd start() is a no-op.
- stop()            : SIGTERM via os.killpg on the process group, then SIGKILL
                      after a 5s grace period.
- status()          : {running, port, pid, uptime_s, restart_count}
- wait_ready()      : poll GET http://127.0.0.1:{port}/ until 200 (or timeout).
- reset_bootstrap() : force-rewrite flows.json with the bootstrap tab.
- _maybe_restart()  : supervisor tick — if proc died, respawn up to
                      MAX_RESTARTS_PER_WINDOW times in RESTART_WINDOW_S seconds.

Crash-loop guard: if a child dies MAX_RESTARTS_PER_WINDOW times within
RESTART_WINDOW_S, _maybe_restart stops respawning and logs to stderr. This
prevents an infinite restart loop from filling logs / burning CPU.
"""
from __future__ import annotations

import json
import os
import shutil
import signal
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


# ── Configuration constants ─────────────────────────────

DEFAULT_PORT = 1880
DEFAULT_USER_DIR = Path.home() / ".1052os" / "node-red"
DEFAULT_GATEWAY_API_URL = "http://127.0.0.1:8765"

# Crash-loop guard thresholds
MAX_RESTARTS_PER_WINDOW = 5
RESTART_WINDOW_S = 60.0

# Grace period for SIGTERM → SIGKILL escalation
STOP_TIMEOUT_S = 5.0


# ── Module-level helpers ────────────────────────────────


def _bootstrap_flow(gateway_api_url: str) -> list[dict]:
    """Return a minimal 1-tab flow that POSTs a tick to /api/td/insert.

    Seeded once on first start; never overwritten unless reset_bootstrap() is
    called explicitly. Users can delete or modify the tab — the seed logic
    treats existing flows.json as untouchable.

    Tab label: ``1052os-bootstrap`` — easy to spot in the editor sidebar.
    """
    url = f"{gateway_api_url.rstrip('/')}/api/td/insert"
    return [
        {
            "id": "1052os-bootstrap",
            "type": "tab",
            "label": "1052os-bootstrap",
            "disabled": False,
            "info": "Auto-seeded by 1052-OS gateway. Delete to disable, or call\n"
                    "POST /api/nodered/reset-bootstrap to regenerate this tab.",
        },
        {
            "id": "b_inj",
            "type": "inject",
            "z": "1052os-bootstrap",
            "name": "tick (5s)",
            "props": [{"p": "payload"}, {"p": "topic", "vt": "str"}],
            "repeat": "5",
            "crontab": "",
            "once": True,
            "onceDelay": "0.2",
            "topic": "1052os-bootstrap",
            "payload": json.dumps({
                "site": "default",
                "device": "sim",
                "tag": "temp",
                "value": 21.5,
            }),
            "payloadType": "json",
            "x": 200,
            "y": 120,
            "wires": [["b_http"]],
        },
        {
            "id": "b_fn",
            "type": "function",
            "z": "1052os-bootstrap",
            "name": "→ /api/td/insert body",
            "func": (
                "// The inject payload IS the body. Just re-emit on msg.payload.\n"
                "msg.payload = msg.payload;\n"
                "return msg;"
            ),
            "outputs": 1,
            "noerr": 0,
            "initialize": "",
            "finalize": "",
            "libs": [],
            "x": 400,
            "y": 120,
            "wires": [["b_http"]],
        },
        {
            "id": "b_http",
            "type": "http request",
            "z": "1052os-bootstrap",
            "name": "POST /api/td/insert",
            "method": "POST",
            "ret": "obj",
            "paytoqs": "ignore",
            "url": url,
            "tls": "",
            "persist": False,
            "proxy": "",
            "authType": "",
            "headers": [],
            "x": 640,
            "y": 120,
            "wires": [[]],
        },
    ]


def _default_settings(port: int) -> str:
    """Minimal settings.js — anonymous editor, no auth, flowFile flows.json."""
    return f"""/**
 * Auto-generated by 1052-OS gateway. Edit carefully — re-runs of
 * nodered_runtime.start() will NOT overwrite this file. Delete it
 * to regenerate.
 */
module.exports = {{
    uiPort: {port},
    uiHost: "127.0.0.1",
    flowFile: "flows.json",
    credentialSecret: "1052os-change-me-in-prod",
    // No adminAuth — intended for local dev. Add username/password in prod.
    adminAuth: null,
    httpAdminRoot: "/",
    httpNodeRoot: "/api/",
    // Keep logging quiet unless something goes wrong.
    logging: {{
        console: {{
            level: "info",
            metrics: false,
            audit: false,
        }},
    }},
}};
"""


def _port_in_use(port: int, host: str = "127.0.0.1") -> bool:
    """Return True when another process is already listening on host:port."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.settimeout(0.25)
        return sock.connect_ex((host, port)) == 0


# ── Runtime class ───────────────────────────────────────


class NodeRedRuntime:
    """Subprocess manager for an embedded ``node-red`` instance.

    The runtime is process-local: each gateway process owns exactly one
    Node-RED subprocess. The class is *not* thread-safe by design — calls
    to start/stop are expected to come from a single owner (FastAPI lifespan).
    """

    def __init__(
        self,
        user_dir: str | Path | None = None,
        port: int = DEFAULT_PORT,
        gateway_api_url: str = DEFAULT_GATEWAY_API_URL,
        log_path: str | Path | None = None,
    ):
        self.user_dir = Path(
            user_dir or os.environ.get("NODERED_USER_DIR") or DEFAULT_USER_DIR
        )
        self.user_dir.mkdir(parents=True, exist_ok=True)
        self.port = int(os.environ.get("NODERED_PORT", port))
        self.gateway_api_url = os.environ.get("GATEWAY_API_URL", gateway_api_url)
        self.log_path = Path(log_path) if log_path is not None else (
            self.user_dir / "gateway.log"
        )

        # Process state
        self._proc: subprocess.Popen | None = None
        self._started_at: float | None = None
        self._last_error: str | None = None

        # Supervisor state
        self._restart_history: list[float] = []
        self._supervisor_thread = None

    # ── Prerequisite check ────────────────────────────

    def _ensure_prerequisites(self) -> None:
        """Verify node + node-red are on PATH; install node-red if missing.

        Raises RuntimeError when node itself is missing — that's a fatal
        config error (user has to install Node.js themselves).
        """
        if shutil.which("node") is None:
            raise RuntimeError(
                "Node.js not found on PATH. Install Node.js 18+ from "
                "https://nodejs.org/ before starting the gateway."
            )
        if shutil.which("node-red") is None:
            # Bootstrap node-red globally. This is the slow path on first run
            # (~30-60s) — print so the user knows why startup is quiet.
            print(
                "[nodered] node-red not found, installing via npm...",
                file=sys.stderr,
            )
            subprocess.run(
                ["npm", "install", "-g", "node-red"],
                check=True,
            )

    # ── Seeding ──────────────────────────────────────

    def _seed_bootstrap_if_missing(self) -> None:
        """Write flows.json with the bootstrap tab ONLY if it doesn't exist.

        We never clobber user-edited flows — once they hit Deploy in the
        editor, that file is theirs.
        """
        flows_path = self.user_dir / "flows.json"
        if flows_path.exists():
            return
        flows_path.write_text(json.dumps(_bootstrap_flow(self.gateway_api_url)))

    def _write_settings_if_missing(self) -> None:
        """Write settings.js with the configured uiPort if it doesn't exist."""
        settings_path = self.user_dir / "settings.js"
        if settings_path.exists():
            return
        settings_path.write_text(_default_settings(self.port))

    def reset_bootstrap(self) -> None:
        """Force-rewrite flows.json with the bootstrap tab (debug endpoint).

        This is a one-shot dev helper. In production the user manages flows
        from the editor; this method exists so the support team can recover
        from a broken flows.json without ssh-ing into the box.
        """
        flows_path = self.user_dir / "flows.json"
        flows_path.write_text(json.dumps(_bootstrap_flow(self.gateway_api_url)))

    # ── Spawn / lifecycle ────────────────────────────

    def start(self) -> None:
        """Start Node-RED. Idempotent — 2nd call is a no-op while running."""
        if self._proc is not None and self._proc.poll() is None:
            return  # already running
        self._ensure_prerequisites()
        self._write_settings_if_missing()
        self._seed_bootstrap_if_missing()
        if _port_in_use(self.port):
            self._last_error = f"Node-RED port {self.port} already in use"
            raise RuntimeError(self._last_error)

        cmd = [
            "node-red",
            "--userDir", str(self.user_dir),
            "--port", str(self.port),
            "--settings", str(self.user_dir / "settings.js"),
        ]
        # start_new_session=True puts node-red in its own process group so we
        # can SIGTERM the whole group on stop (defeats the shell-wrapper
        # parent-process trick node-red uses by default).
        log_file = open(self.log_path, "ab")
        self._proc = subprocess.Popen(
            cmd,
            stdout=log_file,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
        self._started_at = time.time()
        self._last_error = None

        # Start supervisor in background — daemon thread, exits naturally when
        # stop() is called.
        if self._supervisor_thread is None or not self._supervisor_thread.is_alive():
            import threading
            self._supervisor_thread = threading.Thread(
                target=self._supervise_loop,
                daemon=True,
                name="nodered-supervisor",
            )
            self._supervisor_thread.start()

    def stop(self, timeout: float = STOP_TIMEOUT_S) -> None:
        """Send SIGTERM to the process group, escalate to SIGKILL after timeout.

        Because we Popen with ``start_new_session=True``, the child is the
        leader of its own process group — its pid equals its pgid. We can
        therefore pass ``proc.pid`` directly to ``os.killpg`` without first
        calling ``os.getpgid`` (which would fail in unit tests where proc is
        a MagicMock).
        """
        proc = self._proc
        if proc is None:
            return
        try:
            os.killpg(proc.pid, signal.SIGTERM)
        except (ProcessLookupError, PermissionError):
            pass
        try:
            proc.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            try:
                os.killpg(proc.pid, signal.SIGKILL)
            except (ProcessLookupError, PermissionError):
                pass
            proc.wait(timeout=2.0)
        self._proc = None
        self._started_at = None

    def _supervise_loop(self) -> None:
        """Watch the child; on crash, respawn unless we're in a loop."""
        while self._proc is not None:
            proc = self._proc
            if proc.poll() is not None:
                # Child died.
                self._maybe_restart()
                if self._proc is None:
                    return
                continue
            time.sleep(1.0)

    def _maybe_restart(self) -> None:
        """Crash-loop guard: max MAX_RESTARTS_PER_WINDOW respawns per window."""
        now = time.time()
        # Drop entries outside the window.
        self._restart_history = [
            t for t in self._restart_history if now - t < RESTART_WINDOW_S
        ]
        if len(self._restart_history) >= MAX_RESTARTS_PER_WINDOW:
            print(
                f"[nodered] crash loop detected "
                f"({len(self._restart_history)} restarts in "
                f"{RESTART_WINDOW_S}s). Giving up. Check "
                f"{self.log_path} for root cause.",
                file=sys.stderr,
            )
            self._proc = None
            return
        self._restart_history.append(now)
        try:
            self.start()
        except Exception as e:
            print(f"[nodered] restart failed: {e}", file=sys.stderr)
            self._last_error = str(e)
            self._proc = None

    # ── Status / readiness ───────────────────────────

    def is_running(self) -> bool:
        return self._proc is not None and self._proc.poll() is None

    def status(self) -> dict[str, Any]:
        running = self.is_running()
        return {
            "running": running,
            "port": self.port,
            "pid": self._proc.pid if running and self._proc else None,
            "uptime_s": (
                int(time.time() - self._started_at)
                if running and self._started_at is not None
                else None
            ),
            "restart_count": len(self._restart_history),
            "last_error": self._last_error,
        }

    def wait_ready(self, timeout: float = 30.0, poll_interval: float = 0.5) -> bool:
        """Poll GET http://127.0.0.1:{port}/ until 200 or timeout.

        Returns True once Node-RED's HTTP root responds. Used after start()
        to gate "open editor" / "deploy flow" actions in the UI.
        """
        url = f"http://127.0.0.1:{self.port}/"
        deadline = time.time() + timeout
        while time.time() < deadline:
            try:
                with urllib.request.urlopen(url, timeout=2.0) as resp:
                    if getattr(resp, "status", 200) == 200:
                        return True
            except (urllib.error.URLError, ConnectionError, OSError):
                pass
            time.sleep(poll_interval)
        return False

    # ── Admin API helpers ───────────────────────────────

    def _api_url(self, path: str) -> str:
        return f"http://127.0.0.1:{self.port}{path}"

    def _request_json(self, method: str, path: str, body: Any | None = None) -> Any:
        data = None if body is None else json.dumps(body).encode("utf-8")
        req = urllib.request.Request(
            self._api_url(path),
            data=data,
            method=method,
            headers={
                "Content-Type": "application/json",
                "Node-RED-API-Version": "v2",
            },
        )
        with urllib.request.urlopen(req, timeout=10.0) as resp:
            raw = resp.read()
        if not raw:
            return None
        return json.loads(raw.decode("utf-8"))

    def list_flows(self) -> list[dict[str, Any]]:
        """Return the current Node-RED flow array via Admin API."""
        payload = self._request_json("GET", "/flows")
        if isinstance(payload, dict) and "flows" in payload:
            return payload["flows"]
        return payload or []

    def apply_flows(self, flows: list[dict[str, Any]]) -> dict[str, Any]:
        """Deploy a full flow array to Node-RED and persist it to flows.json."""
        payload = {"flows": flows}
        try:
            result = self._request_json("POST", "/flows", payload)
            return {"posted_to_nodered": True, "nodered_error": None, "count": len(flows), "result": result}
        except Exception as exc:
            flows_path = self.user_dir / "flows.json"
            flows_path.write_text(json.dumps(flows))
            return {"posted_to_nodered": False, "nodered_error": str(exc), "count": len(flows)}

    def install_module(self, module: str) -> dict[str, Any]:
        """Install a Node-RED contrib module into this runtime's userDir."""
        if not module.startswith("node-red-") and not module.startswith("@"):
            raise ValueError("module must be a Node-RED package name")
        result = subprocess.run(
            ["npm", "install", module],
            cwd=self.user_dir,
            text=True,
            capture_output=True,
            timeout=180,
        )
        if result.returncode != 0:
            raise RuntimeError((result.stderr or result.stdout).strip())
        return {"module": module, "stdout": result.stdout[-4000:]}
